name: books_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  snap_scroll_physics: ^0.0.1+3
  scroll_snap_list: ^0.9.1
  syncfusion_flutter_gauges: ^20.4.49
  flutter_svg: ^2.0.0+1
  syncfusion_flutter_charts: ^20.4.49

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/